name: bmi543

channels: 
    - defaults 
    - pytorch 
    - conda-forge

dependencies:
    - python=3.9
    - matplotlib
    - pytorch=1.10
    - torchvision
    - numpy 
    - seaborn
    - ffmpeg
    - scikit-learn
    - pip
    - pip:
      - notebook
      - ipykernel
      - celluloid
